name: Terraform Validation

on:
  push:
    branches:
      - master  # O cambia a "main" si esa es tu rama principal

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Validate Terraform code
        run: terraform validate
